import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-family-heading',
  fallback: ['--font-family-sans'],
  weight: ['400', '500'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Nextjs Markdown Blog',
  description: 'Generated by create next app and markdown-to-jsx',
  icons: {
    icon: 'next.svg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-customBlue`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
